#!/bin/sh

interface="wlan0"

if grep -xq 'up' /sys/class/net/$interface/operstate 2>/dev/null; then
	wifiicon="󰖩  "
elif grep -xq 'down' /sys/class/net/$interface/operstate 2>/dev/null; then
	wifiicon="󰖪  "
fi

echo "$wifiicon"
